"""Geradores de combinações dirigidos por regras controladas."""

from perfis_metalicos.combinations.generator import (
    CombinationFamily,
    CombinationRuleSet,
    FactorRule,
    LoadCombination,
    TermRole,
    generate_combinations,
)
from perfis_metalicos.combinations.nbr8681_2025 import (
    COMBINATION_FACTORS,
    EXCEPTIONAL_ACTION_FACTOR,
    FIRE_PSI_2_REDUCTION,
    GROUPED_VARIABLE_GAMMA_FACTORS,
    PERMANENT_FACTORS,
    SERVICE_PERMANENT_FACTOR,
    VARIABLE_GAMMA_FACTORS_SEPARATE,
    ActionGrouping,
    EffectiveAccompanyingFactor,
    FirePsi2Treatment,
    GroupedAtmosphericTemperatureTreatment,
    NBR8681ExceptionalCategory,
    NBR8681PermanentCategory,
    NBR8681VariableClassification,
    NBR8681VariableGammaCategory,
    NBR8681VariablePsiCategory,
    build_pending_nbr8681_2025_rule_set,
    category_kind,
)

__all__ = [
    "ActionGrouping",
    "COMBINATION_FACTORS",
    "CombinationFamily",
    "CombinationRuleSet",
    "EffectiveAccompanyingFactor",
    "EXCEPTIONAL_ACTION_FACTOR",
    "FIRE_PSI_2_REDUCTION",
    "FactorRule",
    "FirePsi2Treatment",
    "GROUPED_VARIABLE_GAMMA_FACTORS",
    "GroupedAtmosphericTemperatureTreatment",
    "LoadCombination",
    "NBR8681ExceptionalCategory",
    "NBR8681PermanentCategory",
    "NBR8681VariableClassification",
    "NBR8681VariableGammaCategory",
    "NBR8681VariablePsiCategory",
    "PERMANENT_FACTORS",
    "SERVICE_PERMANENT_FACTOR",
    "TermRole",
    "VARIABLE_GAMMA_FACTORS_SEPARATE",
    "build_pending_nbr8681_2025_rule_set",
    "category_kind",
    "generate_combinations",
]
